site_name: YoungKyun_Kim

theme: material

nav:
  - Young Kyun Kim: index.md
  - Research: research.md
  - Activity: activity.md

extra_css:
  - stylesheets/extra.css

#git add . && git commit -m "update" && git push && mkdocs gh-deploy