site_name: Young Kyun Kim

theme: material

nav:
  - Home: index.md
  - Research: research.md
  - Activity: activity.md

extra_css:
  - stylesheets/extra.css

#git add . && git commit -m "update" && git push && mkdocs gh-deploy